### ISSUE TITLE
Nearest neighbour interpolation in `affine_transform` 

### ISSUE THREAD

**Issue by VolkerH** [maweigert/gputools#13]
It appears there is a bug in
https://github.com/maweigert/gputools/blob/master/gputools/transforms/kernels/transformations.cl

When selecting nearest neighbour the preprocessor defines `SAMPLERFILTER` but what is needed is `SAMPLER_FILTER`. Credits to @jni for spotting this.
![image](https://user-images.githubusercontent.com/2210044/49488743-05c23380-f89c-11e8-8acf-bc6107018c82.png)

**Comment by maweigert** [comment]
Hi @VolkerH,

this was indeed the case - thank for spotting! 
Should be fixed in the latest develop branch.
Thanks again!
