### ISSUE TITLE
sampler unused in interpolate3?

### ISSUE THREAD

**Issue by jni** [maweigert/gputools#20]
I noticed that the sampler variable is used by fill_patch3 in conv_spatial3.cl but not by interpolate3, where it is instantiated but unused:

https://github.com/maweigert/gputools/blob/6ab26efeb05dceef74cf13aadeeeb9b009b529dd/gputools/convolve/kernels/conv_spatial3.cl#L113

Is this intentional?

**Comment by maweigert** [comment]
Thanks, you're right. Should be fixed now.
