### ISSUE TITLE
Python 3.9 compatibility

### ISSUE THREAD

**Issue by parthnatekar** [maweigert/gputools#27]
Hi, I am unable to install gputools with python 3.9.7.

Is there a plan to make gputools compatible for this?

**Comment by maweigert** [comment]
Hi, I have not problem installing it with python 3.9.7 - what issue are you facing? What OS?

**Comment by parthnatekar** [comment]
Hi,

I'm trying to install in a conda env on Ubuntu 18.04. Conda seems to be finding Here is the stack trace;

'
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - gputools -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']

Your python: conda-forge/linux-64::python==3.9.7=hb7a2778_2_cpython

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.
'

**Comment by tlambert03** [comment]
are you, by chance trying to install gpu tools via conda with `conda install -c talley gputools`?  or are you installing from pip?

**Comment by parthnatekar** [comment]
Hi, sorry for the incomplete information in the previous comment. I am using conda install. 

However, I was able to use pip to get around the issue for the moment - this is breaking some other dependencies but I have a makeshift solution and I am closing this. Can you please take a look at why the ```conda install -c talley gputools``` is not working for python 3.9 (if it is supported already).

**Comment by tlambert03** [comment]
yeah, that conda package isn't really really being maintained. @maweigert, we should get this on conda-forge. is that something you've done before?  or shall I open a PR?  (happy to continue help maintaining that... but it would auto-update with your pypi package much easier)

**Comment by maweigert** [comment]
Hi @tlambert03 

> we should get this on conda-forge. is that something you've done before?

Ha, thats been on the list - haven't done it yet and was shying away from the extra work whilst pip is working just fine :) The package itself is pretty stable so it might not be too much work though...
