### ISSUE TITLE
get on conda-forge

### ISSUE THREAD

**Issue by tlambert03** [maweigert/gputools#28]
hey @maweigert, I can take care of getting it on conda-forge (useful if anything else on conda-forge wants to depend on this).

But it would be helpful if you added an sdist to your pypi distribution.  Can you add `python3 setup.py bdist_wheel sdist` to your build_pypi script and update the `twine upload dist/*whl` to also upload the sdist as well?

**Comment by maweigert** [comment]
Thanks! 

> Can you add `python3 setup.py bdist_wheel sdist` to your build_pypi script and update the `twine upload dist/*whl` to also upload the sdist as well?

Should be done now: https://pypi.org/project/gputools/#files

**Comment by tlambert03** [comment]
awesome!  thank you!
