### ISSUE TITLE
New releases to gputools?

### ISSUE THREAD

**Issue by AhmetCanSolak** [maweigert/gputools#32]
hello @maweigert , happy new year!

I was wondering your plans on the future of `gputools`. Are you planning to make new versions?

I found small incompatibilities with recent NumPy and some parts of the repo, like:
https://github.com/maweigert/gputools/blob/4ca3b013879c18cf8d4c8b1d91b5681a3287616c/gputools/core/ocltypes.py#L29
giving an error on `numpy>=1.24`.  I like to patch this, and I believe I can help with a couple more small items around the repo, like compatibility with different python versions and so.

I am happy to make PRs to this repo to help, or I can fork it if you are planning to archive this repository.  Please advise me on what you like me to do.

**Comment by maweigert** [comment]
Hi @AhmetCanSolak 

Happy new year too! Yes, I will still provide bugfix versions, so thank for pointing out that issue!
I changed the type to `np.bool_` in eb513300, which should take care of this. However, one of the dependencies (reikna) has the [same issue](https://github.com/fjarri/reikna/pull/64), so we need to wait for proper `numpy=1.24` support. I therefore pinned the numpy version to `numpy<1.24` and created a new pypi verison `0.2.14` as a workaround (https://pypi.org/project/gputools/).
